name: Create package

on:
  workflow_call:

jobs:
  package:
    name: Package
    runs-on: ubuntu-latest
    steps:
        - name: Checkout code
          uses: actions/checkout@v4
        - name: Run the package command
          run: |
            curl -ssL https://magic.modular.com | bash
            source $HOME/.bash_profile
            magic run mojo package src/libc -o libc.mojopkg

        - name: Upload package as artifact
          uses: actions/upload-artifact@v4
          with:
            name: libc-package
            path: libc.mojopkg
