name: Run the testing suite

on:
  workflow_call:

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run the test suite
        run: |
          curl -ssL https://magic.modular.com | bash
          source $HOME/.bash_profile
          magic run mojo run_tests.mojo
